"""update

Revision ID: 0a767e578bc3
Revises: bd98e4912a7f
Create Date: 2023-12-27 12:24:33.134465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a767e578bc3'
down_revision: Union[str, None] = 'bd98e4912a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model', sa.Column('mark', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='For marking purposes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_model', 'mark')
    # ### end Alembic commands ###
