"""update

Revision ID: 61d0a3d74df6
Revises: 0a767e578bc3
Create Date: 2023-12-28 15:39:35.090030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d0a3d74df6'
down_revision: Union[str, None] = '0a767e578bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model', sa.Column('mark2', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='For marking purposes 2'))
    op.add_column('vehicle_model', sa.Column('mark3', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='For marking purposes 3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_model', 'mark3')
    op.drop_column('vehicle_model', 'mark2')
    # ### end Alembic commands ###
