"""update

Revision ID: aa85efe7a12b
Revises: 9b815626eb5a
Create Date: 2023-10-18 14:46:47.403318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa85efe7a12b'
down_revision: Union[str, None] = '9b815626eb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('scraped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'scraped_at')
    # ### end Alembic commands ###
