"""Create a baseline migrations

Revision ID: 8ebb1f836ee2
Revises: 
Create Date: 2023-09-27 16:05:29.044482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebb1f836ee2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('make_country_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('make',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('make_country_region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['make_country_region_id'], ['make_country_region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'make_country_region_id')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('sub_model', sa.String(length=255), nullable=False),
    sa.Column('engine_code', sa.String(length=32), nullable=True),
    sa.Column('chassis_code', sa.String(length=32), nullable=True),
    sa.Column('engine_displacement', sa.Integer(), nullable=False),
    sa.Column('engine_displacment_unit', sa.String(length=16), nullable=False),
    sa.Column('engine_output', sa.Integer(), nullable=False),
    sa.Column('engine_output_unit', sa.String(length=16), nullable=False),
    sa.Column('production_start_date', sa.Date(), nullable=True),
    sa.Column('production_end_date', sa.Date(), nullable=True),
    sa.Column('shift_type', sa.String(length=8), nullable=False),
    sa.Column('fuel_source_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuel_source_id'], ['fuel_source.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['make.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('make')
    op.drop_table('vehicle_type')
    op.drop_table('make_country_region')
    op.drop_table('fuel_source')
    # ### end Alembic commands ###
