"""update

Revision ID: 1f6267a4f349
Revises: c66e665c3576
Create Date: 2023-11-07 12:09:11.733280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f6267a4f349'
down_revision: Union[str, None] = 'c66e665c3576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', mysql.BIGINT(), nullable=False, comment='pk'),
    sa.Column('year', mysql.YEAR(), nullable=False, comment='年份'),
    sa.Column('make', mysql.VARCHAR(length=64), nullable=False, comment='車廠'),
    sa.Column('model', mysql.VARCHAR(length=128), nullable=False, comment='型號'),
    sa.Column('sub_model', mysql.VARCHAR(length=255), nullable=False, comment='子型號'),
    sa.Column('price', mysql.FLOAT(), server_default=sa.text('0'), nullable=False, comment='售價'),
    sa.Column('output', mysql.VARCHAR(length=128), server_default='', nullable=False, comment='子型號'),
    sa.Column('displacement', mysql.VARCHAR(length=128), server_default='', nullable=False, comment='排氣量'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
