"""update

Revision ID: 47d236bd558f
Revises: 5aadcd1c998f
Create Date: 2023-11-20 00:44:12.503670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47d236bd558f'
down_revision: Union[str, None] = '5aadcd1c998f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model', sa.Column('auto_data_id', mysql.BIGINT(), nullable=True, comment='Auto Data ID'))
    op.add_column('vehicle_model', sa.Column('tire_rack_id', mysql.BIGINT(), nullable=True, comment='Tire Rack ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_model', 'tire_rack_id')
    op.drop_column('vehicle_model', 'auto_data_id')
    # ### end Alembic commands ###
