"""update

Revision ID: 5aadcd1c998f
Revises: 9bd23bb4a0d6
Create Date: 2023-11-08 21:47:47.152972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5aadcd1c998f'
down_revision: Union[str, None] = '9bd23bb4a0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model', sa.Column('output', mysql.CHAR(length=16), nullable=True, comment='輸出'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_model', 'output')
    # ### end Alembic commands ###
