"""update

Revision ID: bd98e4912a7f
Revises: 4d21a5b04f0e
Create Date: 2023-12-07 15:24:57.318104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd98e4912a7f'
down_revision: Union[str, None] = '4d21a5b04f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_model', 'auto_data_id',
               existing_type=mysql.BIGINT(),
               type_=mysql.INTEGER(),
               existing_comment='Auto Data ID',
               existing_nullable=True)
    op.alter_column('vehicle_model', 'tire_rack_id',
               existing_type=mysql.BIGINT(),
               type_=mysql.INTEGER(),
               existing_comment='Tire Rack ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_model', 'tire_rack_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(),
               existing_comment='Tire Rack ID',
               existing_nullable=True)
    op.alter_column('vehicle_model', 'auto_data_id',
               existing_type=mysql.INTEGER(),
               type_=mysql.BIGINT(),
               existing_comment='Auto Data ID',
               existing_nullable=True)
    # ### end Alembic commands ###
