"""update

Revision ID: c57a56964de5
Revises: 47d236bd558f
Create Date: 2023-11-21 14:32:51.207654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c57a56964de5'
down_revision: Union[str, None] = '47d236bd558f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model', sa.Column('yahoo_id', mysql.BIGINT(), nullable=True, comment='Yahoo ID'))
    op.alter_column('vehicle_model', 'output',
               existing_type=mysql.CHAR(length=16),
               type_=mysql.VARCHAR(length=64),
               comment='輸出 (馬力)',
               existing_comment='輸出',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_model', 'output',
               existing_type=mysql.VARCHAR(length=64),
               type_=mysql.CHAR(length=16),
               comment='輸出',
               existing_comment='輸出 (馬力)',
               existing_nullable=True)
    op.drop_column('vehicle_model', 'yahoo_id')
    # ### end Alembic commands ###
