"""update

Revision ID: 4f845bfd63b2
Revises: a81cc75f2a70
Create Date: 2023-11-21 16:48:47.236337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f845bfd63b2'
down_revision: Union[str, None] = 'a81cc75f2a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('selected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'selected')
    # ### end Alembic commands ###
