"""update

Revision ID: f2e04d2207ca
Revises: 82f7f2c17da4
Create Date: 2023-11-14 14:46:55.979090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e04d2207ca'
down_revision: Union[str, None] = '82f7f2c17da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('start_of_perduction_year', sa.Integer(), nullable=True))
    op.add_column('car', sa.Column('end_of_perduction_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'end_of_perduction_year')
    op.drop_column('car', 'start_of_perduction_year')
    # ### end Alembic commands ###
