"""Create a baseline migrations

Revision ID: 8591428dcdc9
Revises: 6ddc2504d10e
Create Date: 2023-09-28 17:27:43.884597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8591428dcdc9'
down_revision: Union[str, None] = '6ddc2504d10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('engine', 'change_interval',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('engine', 'capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('engine', 'viscosity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('engine', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transmission', 'change_interval',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('transmission', 'capacity',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('transmission', 'viscosity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transmission', 'viscosity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('transmission', 'capacity',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('transmission', 'change_interval',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('engine', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('engine', 'viscosity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('engine', 'capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('engine', 'change_interval',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
