"""update

Revision ID: fc28759cd94f
Revises: 8ebb1f836ee2
Create Date: 2023-09-28 11:03:57.768151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc28759cd94f'
down_revision: Union[str, None] = '8ebb1f836ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooling_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_interval', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.String(length=32), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('change_interval', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.String(length=32), nullable=False),
    sa.Column('viscosity', sa.String(length=255), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hydraulic_brake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_interval', sa.String(length=32), nullable=False),
    sa.Column('check_interval', sa.String(length=32), nullable=False),
    sa.Column('dot', sa.String(length=128), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_steering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_interval', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.String(length=32), nullable=False),
    sa.Column('atf', sa.String(length=128), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('change_interval', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.String(length=32), nullable=False),
    sa.Column('viscosity', sa.String(length=255), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_constraint('car_fuel_source_id_fkey', 'car', type_='foreignkey')
    op.drop_column('car', 'fuel_source_id')
    op.drop_table('fuel_source')

    op.drop_constraint('car_make_id_fkey', 'car', type_='foreignkey')
    op.drop_column('car', 'make_id')
    op.drop_table('make')

    op.drop_constraint('car_vehicle_type_id_fkey', 'car', type_='foreignkey')
    op.drop_column('car', 'vehicle_type_id')
    op.drop_table('vehicle_type')

    op.add_column('car', sa.Column('make', sa.String(length=32), nullable=False))


    op.drop_column('car', 'shift_type')
    op.drop_column('car', 'engine_displacement')
    op.drop_column('car', 'engine_output_unit')
    op.drop_column('car', 'production_start_date')
    op.drop_column('car', 'engine_output')
    op.drop_column('car', 'production_end_date')
    op.drop_column('car', 'chassis_code')
    op.drop_column('car', 'engine_code')
    op.drop_column('car', 'engine_displacment_unit')

    # op.drop_table('make_country_region')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('engine_displacment_unit', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('engine_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('fuel_source_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('chassis_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('production_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('engine_output', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('production_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('engine_output_unit', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('vehicle_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('engine_displacement', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('shift_type', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.create_foreign_key('car_fuel_source_id_fkey', 'car', 'fuel_source', ['fuel_source_id'], ['id'])
    op.create_foreign_key('car_vehicle_type_id_fkey', 'car', 'vehicle_type', ['vehicle_type_id'], ['id'])
    op.create_foreign_key('car_make_id_fkey', 'car', 'make', ['make_id'], ['id'])
    op.drop_column('car', 'make')
    op.create_table('vehicle_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicle_type_pkey'),
    sa.UniqueConstraint('name', name='vehicle_type_name_key')
    )
    op.create_table('make',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('make_country_region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['make_country_region_id'], ['make_country_region.id'], name='make_make_country_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='make_pkey'),
    sa.UniqueConstraint('name', 'make_country_region_id', name='make_name_make_country_region_id_key'),
    sa.UniqueConstraint('name', name='make_name_key')
    )
    op.create_table('make_country_region',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='make_country_region_pkey'),
    sa.UniqueConstraint('name', name='make_country_region_name_key')
    )
    op.create_table('fuel_source',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fuel_source_pkey'),
    sa.UniqueConstraint('name', name='fuel_source_name_key')
    )
    op.drop_table('transmission')
    op.drop_table('power_steering')
    op.drop_table('hydraulic_brake')
    op.drop_table('engine')
    op.drop_table('cooling_system')
    # ### end Alembic commands ###
